name: Data Consistency Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  consistency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run consistency check
      run: cross_check_correspondents.py