name: Data Consistency Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  consistency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run consistency check
      id: run-check
      run: |
        python cross_check_correspondents.py

    - name: Create badge
      if: failure()
      run: |
        echo "![Data Consistency Check](https://img.shields.io/badge/consistency-failed-red)" > badge.md

    - name: Create badge
      if: success()
      run: |
        echo "![Data Consistency Check](https://img.shields.io/badge/consistency-passed-brightgreen)" > badge.md

    - name: Display result
      run: cat badge.md
