name: Erasmus Budé Intersections - Run R Scripts and Save Outputs

on:
  workflow_run:
    workflows: ["Erasmus Budé Intersections - Setup MySQL, Import Data, and Run Queries"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: dataset-pipeline-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest

    container:
      image: rocker/geospatial:4.3.1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
  
    - name: Install Required R Packages
      run: |
        R -e 'install.packages("leaflet", repos ="https://packagemanager.posit.co/cran/latest")'
        R -e 'install.packages(c("svglite", "ggrepel", "patchwork", "lubridate", "classInt", "htmlwidgets", "htmltools", "igraph", "rgexf", "ndtv"), repos ="https://packagemanager.posit.co/cran/latest")'
        R -e 'install.packages("leaflet.extras", repos ="https://packagemanager.posit.co/cran/latest")'
          
    - name: Replace folder specification for setwd() in R Scripts
      run: |
        find intersections_budé_erasmus/r_scripts/ -type f -name "*.R" -exec sed -i 's|setwd("../query_results/")|setwd("intersections_budé_erasmus/query_results/")|g' {} +
        find intersections_budé_erasmus/r_scripts/ -type f -name "*.R" -exec sed -i 's|setwd("../r_plots/")|setwd("/__w/corr_data/corr_data/intersections_budé_erasmus/r_plots/")|g' {} +
    
    - name: Run R Scripts (exclude network_animations)
      run: |
        find intersections_budé_erasmus/r_scripts/ -type f -name "*.R" ! -path "*/create_network_animations/*" | while read script; do
          echo "📥 Running script: $script"
          Rscript "$script"
        done

    - name: Revert folder specification for setwd() in R Scripts
      run: |
        find intersections_budé_erasmus/r_scripts/ -type f -name "*.R" -exec sed -i 's|setwd("intersections_budé_erasmus/query_results/")|setwd("../query_results/")|g' {} +
        find intersections_budé_erasmus/r_scripts/ -type f -name "*.R" -exec sed -i 's|setwd("/__w/corr_data/corr_data/intersections_budé_erasmus/r_plots/")|setwd("../r_plots/")|g' {} +
      
#   - name: Upload R Plots
#     uses: actions/upload-artifact@v4
#     with:
#       name: r-plots
#       path: intersections_budé_erasmus/r_plots/

#   - name: Upload Leaflet Maps
#     uses: actions/upload-artifact@v4
#     with:
#       name: leaflet-maps
#       path: intersections_budé_erasmus/leaflet_maps/
#
    - name: Configure Git
      run: |
        git config --global user.name "CKudella"
        git config --global user.email "CKudella@users.noreply.github.com"
        git config --global --add safe.directory /__w/corr_data/corr_data
 
    - name: Commit and push changes
      run: |
        git add -A
        git commit -m "Auto-update r_plots" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ckudella/corr_data.git HEAD:master
