name: Erasmus - Test Refactored R Scripts

on:
  workflow_run:
    workflows: ["Erasmus - Setup MySQL, Import Data, Create DB Dump, and Run Queries"]
    types:
      - completed
  workflow_dispatch:

  group: erasmus-r-scripts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ckudella/corr_data-r-env:r4.5.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run R Scripts
      working-directory: erasmus/r_scripts
      run: |
        find . -type f -name "*.R" ! -name "leaflet_helpers.R" | while read script; do
          echo "📥 Running script: $script"
          Rscript "$script"
        done

    - name: Upload R Plots
      uses: actions/upload-artifact@v4
      with:
        name: r-plots
        path: erasmus/r_plots/

    - name: Upload Leaflet Maps
      uses: actions/upload-artifact@v4
      with:
        name: leaflet-maps
        path: erasmus/leaflet_maps/
